### ISSUE TITLE
Operator _zeros cannot be run

### ISSUE THREAD

**Issue by PetroWu** [Seanlinx/mtcnn#21]
I've encountered this problem with latest version of mxnet:

`mxnet.base.MXNetError: [21:26:49] src/c_api/c_api_ndarray.cc:274: `
`Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered`

Do you have any idea how to solve it?
Thank you~

**Comment by Seanlinx** [comment]
Maybe there's something wrong with your mxnet. I've tested it with v0.9.3 and v0.9.4 but didn't meet this problem. @PetroWu

**Comment by PetroWu** [comment]
Thank you for your reply!
I am using v0.9.4. On mac I disabled cuda and get this error. But on ubuntu with cuda enabled, this error disappeared. However, when I ran `python demo.py`, I got `Segmentation Fault (core dumped)`.
Mxnet is complied with cuda and cudnn, but without openblas. I wonder if your setting of mxnet is the same? Could you please attach you `config.mk` file of your mxnet.

**Comment by Seanlinx** [comment]
I just modified these three lines:
`USE_CUDA = 1`
`USE_CUDA_PATH = /usr/local/cuda`
`USE_CUDNN = 1`

**Comment by PetroWu** [comment]
This issue can be solved by switching from python3.5 to python2.7, while I don't know why...
Thank you for your help!
