### ISSUE TITLE
anno.txt

### ISSUE THREAD

**Issue by zhuhongweiyi** [Seanlinx/mtcnn#3]
Hi, dear writer:
    Thank you for sharing the code.Recently , i'm studying face detection. Could you share me with /wider_annotations/anno.txt?
Thank you very much!

**Comment by Zouhj** [comment]
The author has told how to get the anno.txt. just run wider_annotations/transform.m you can get the anno.txt, besides, you can modify transform.m to get test_anno.txt and val_anno.txt

**Comment by zhuhongweiyi** [comment]
thanks @Zouhj
