### ISSUE TITLE
What kind of data should I give Pnet when generating RNet data using gen_hard_example.py?

### ISSUE THREAD

**Issue by zzmig** [Seanlinx/mtcnn#33]
Dear Lin,
Your work is great for me.

I tried to generate data for Rnet training. But I am by some doubts about this process. What kind of data should I give Pnet when generating RNet data using gen_hard_example.py?Is the 12x12 image used during the Pnet training process or images in WIDER FACE dataset? 
thanks a lot.

**Comment by Seanlinx** [comment]
@zzmig Images in WIDER FACE dataset. The 12x12 images are well trained, what we need is hard examples that Pnet cannot handle.

**Comment by zzmig** [comment]
@Seanlinx, Thank you very much for your response, gave me great help. Now I have been able to train Rnet.
