### ISSUE TITLE
gen_hard_example test_mode Pnet problem

### ISSUE THREAD

**Issue by quickj** [Seanlinx/mtcnn#43]
@Seanlinx  I just want to use gen_hard_example.py --test_mode pnet to get some train data for the next net Rnet. But the defections is empty because the size for Pnet is 12x12,  and the min_face_size is 16 default. should i set the min_face_size to the 12?
current_scale = float(net_size) / self.min_face_size

**Comment by Seanlinx** [comment]
@quickj The detector will rescale the image many times to cover all faces whose sizes are between min_face_size and the shorter side of image. If all the faces' sizes are less than min_face_size in a image, the detection result of this image could be empty, otherwise the detection can't be empty if your Pnet is well trained.

**Comment by kuaikuaikim** [comment]
Thanks @Seanlinx . I found  a assert about:
assert len(det_boxes) == num_of_images, "incorrect detections or ground truths"
but i think this two will never be the same, the det_boxes is trained from  train_12.txt, and the num_of_images is the number of the original images(from anno.txt lines). 
Maybe my wrong opinion. But i really want to know which file is the train file detected by Pnet, to get the Rnet train file.

**Comment by Seanlinx** [comment]
@quickj det_boxes is a list of detection results, each item corresponds to an image, so this two should be equal.  
I don't understand what do you mean by 'train file detected by Pnet', did you mean the detection result of Pnet?

**Comment by kuaikuaikim** [comment]
each item corresponds to an image, you mean an image only contain a face?
'train file detected by Pnet' is the resource been predicted by Pnet. 
'anno_file = './prepare_data/wider_annotations/anno.txt'. is the same anno_file for train and predict ? and this file's line format like this:
**/home/sg/data/WIDER_train/images/0--Parade/0_Parade_Parade_0_1014.jpg 121 379 131 391 245 378 257 392** 
without classification label, does it right?

**Comment by Seanlinx** [comment]
@quickj
1. Each item is a numpy array with a shape of n x 5, n is the number of faces detected.
2. The resource are images in WIDER_train
3. Yes, it's the same file
4. Right

**Comment by kuaikuaikim** [comment]
@Seanlinx Thanks very much. I understood, i make a mistake between the train Pnet  and predict Pnet annotation files. I fix it and running well in my computer.

**Comment by hdjsjyl** [comment]
@kuaikuaikim , Do you know what's the dataset that's used to train the models of author's code? onet-0016.params, pnet-0016.params and rnet-0016.params. Thank you very much.
