### ISSUE TITLE
关于绘制pr曲线

### ISSUE THREAD

**Issue by LinnaWang76** [Seanlinx/mtcnn#51]
你好！我想问下作者提供的pr图是怎么作出来的，我用o-net输出的bbox和score 拿到widerface 的eval-tools上运行，效果非常差……所以应该怎样选取bbox和score

**Comment by Seanlinx** [comment]
@LinnaWang76 I don't know. I didn't evaluate it on WIDER FACE. 
The author provided the parameters used to reproduce their results [here](https://github.com/kpzhang93/MTCNN_face_detection_alignment/blob/master/code/codes/README.txt). But the threshold will not suit this code obviously.

**Comment by LinnaWang76** [comment]
@Seanlinux Thanks

**Comment by hdjsjyl** [comment]
@LinnaWang76 , 请问能把你用来生成wider face提交结果的代码share一下吗， 我跑的时候总是报错：
AttributeError: 'NoneType' object has no attribute 'copy'， 谢谢
